### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by LogicalDash** [gpoulter/python-ngram#10]
The latest version of NGram on PyPI is from 2013 and has at least one real show-stopper bug; its .pop() method never seems to work for me.

Uploading a version 3.3.1 with #8 included would make my deployment process easier, and would smooth out the new user's experience.

**Comment by gpoulter** [comment]
I've taken the opportunity to fix the other outstanding issues, and released new version 3.3.2:

https://pypi.python.org/pypi/ngram

Sorry about the bug in .pop and .remove... they were deleting ngrams multiple times if they occurred multiple times in the provided string, and so failing.
