### ISSUE TITLE
build fails with python 3.9 and setuptools 58.0.2

### ISSUE THREAD

**Issue by adamko147** [gpoulter/python-ngram#15]
setuptools 58.0.2 removed `use_2to3` parameter and fails builds with `use_2to3` parameter. see https://setuptools.readthedocs.io/en/latest/history.html#v58-0-2

Any chance this could be easily fixed? I have to stick to setuptools 58.0.1 until than...

Thanks!

**Comment by gpoulter** [comment]
Hi Adam, thank you. It should be easy to fix, I'll be able to get to it tomorrow.

**Comment by gpoulter** [comment]
Okay, I've the issue by dropping Python 2 support, updating the docs and releasing a new version at https://pypi.org/project/ngram/4.0.1/

**Comment by gpoulter** [comment]
Correction: please use https://pypi.org/project/ngram/4.0.3/  instead

When I changed to using setup.cfg I omitted the py_modules param that included ngram.py in the release, fixed that now.
