### ISSUE TITLE
Last package not working

### ISSUE THREAD

**Issue by droncalveridasnano** [gpoulter/python-ngram#16]
Hello, 

Last package version 4.0.1 is not working in pipy. It seems file ngram.py is not being downloaded. 

thanks.

**Comment by gpoulter** [comment]
I messed up the setup.cfg by omitting py_modules. 

I've yanked the 4.0.0 and 4.0.1 releases, added the py_modules line, tried out a new release on the test PyPI, and uploaded a new release 4.0.3

**Comment by ghost** [comment]
Thanks, it seems it works now!
